 export const RESULT_STATUS = {
  PUBLISHED: "PUBLISHED",
  UNDER_CORRECTION: "UNDER_CORRECTION",
  CORRECTED: "CORRECTED",
};

export const REVIEW_STATUS = {
  PENDING: "PENDING",
  OK: "OK",
  ERROR: "ERROR",
};
